from django.urls import path
from my_app import views
from my_app.api import Driver_Login,Delivered_items,Delivery_documents,Returned_items

urlpatterns = [
    path('',views.sign_in,name='sign_in'),
    path('sign_in_check',views.sign_in_check,name='sign_in_check'),
    path('home/',views.home,name='home'),
    path('admin_register/',views.admin_register,name='admin_register'),
    path('admin_reg_submit/',views.admin_reg_submit,name='admin_reg_submit'),
    path('admin_list/',views.admin_list,name='admin_list'),
    path('update_user/<int:u_id>',views.update_user,name='update_user'),
    path('user_update_submit/',views.user_update_submit,name='user_update_submit'),
    path('delete_user/',views.delete_user,name='delete_user'),
    path('driver_registration/',views.driver_registration,name='driver_registration'),
    path('driver_reg_submit/',views.driver_reg_submit,name='driver_reg_submit'),
    path('driver_list/',views.driver_list,name='driver_list'),
    path('search_driver/',views.search_driver,name='search_driver'),
    path('update_driver/<int:d_id>',views.update_driver,name='update_driver'),
    path('driver_data_update/',views.driver_data_update,name='driver_data_update'),
    path('delete_driver/<int:d_id>',views.delete_driver,name='delete_driver'),
    path('add_tasks/',views.add_tasks,name='add_tasks'),
    path('upload_tasks/',views.upload_tasks,name='upload_tasks'),
    path('live_tasks_table/',views.live_tasks_table,name='live_tasks_table'),
    path('task_sort_by_admin/',views.task_sort_by_admin,name='task_sort_by_admin'),
    path('delete_task/',views.delete_task,name='delete_task'),
    path('view_task/<int:o_id>',views.view_task,name='view_task'),
    path('change_driver/',views.change_driver,name='change_driver'),
    path('change_preference/',views.change_preference,name='change_preference'),
    path('task_list_delete/',views.task_list_delete,name='task_list_delete'),
    path('sign_out/',views.sign_out,name='sign_out'),
    path('driver_login/',Driver_Login.as_view(),name='driver_login'),
    path('delivered_items/',Delivered_items.as_view(),name='delivered_items'),
    path('delivered_tasks/',views.delivered_tasks,name='delivered_tasks'),
    path('view_documents/<int:t_id>',views.view_documents,name='view_documents'),
    path('add_delivery_documents/',Delivery_documents.as_view(),name='add_delivery_documents'),
    path('returned_tasks/',views.returned_tasks,name='returned_tasks'),
    path('returned_items/',Returned_items.as_view(),name='returned_items'),
    path('upload_return_doc/',views.upload_return_doc,name='upload_return_doc'),
    path('return_to_pending/<int:t_id>',views.return_to_pending,name='return_to_pending'),
    path('delete_returned_item/<int:t_id>',views.delete_returned_item,name='delete_returned_item'),
    path('delete_return_docs/<int:id>',views.delete_return_docs,name='delete_return_docs'),
    path('delivery_docs_by_admin/',views.delivery_docs_by_admin,name='delivery_docs_by_admin'),
    path('delete_additional_delivery_doc/<int:id>',views.delete_additional_delivery_doc,name='delete_additional_delivery_doc'),
    path('change_password_submit/',views.change_password_submit,name='change_password_submit'),
]