# Generated by Django 3.1 on 2020-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='admin')),
            ],
        ),
    ]
