# Generated by Django 3.1 on 2020-09-08 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_driver_register_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_register',
            name='driver_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=2, unique=True),
        ),
    ]
