# Generated by Django 3.1 on 2020-09-11 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200908_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_register',
            name='driver_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=20)),
                ('invoice_no', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=50)),
                ('driver_code', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile', models.IntegerField()),
                ('shipping_name', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('alt_contact_no', models.IntegerField()),
                ('client', models.CharField(max_length=20)),
                ('preference', models.IntegerField()),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.admin_register')),
            ],
        ),
    ]
