# Generated by Django 3.1 on 2020-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200911_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20)),
                ('delivered_date', models.DateField()),
                ('delivered_time', models.TimeField()),
                ('task_created_date', models.DateField()),
                ('task_id', models.IntegerField()),
                ('serial_no', models.IntegerField()),
                ('pod_type', models.CharField(max_length=20)),
                ('id_card_no', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=20)),
                ('driver_code', models.CharField(max_length=20)),
                ('invoice_no', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20)),
                ('returned_date', models.DateField()),
                ('returned_time', models.TimeField()),
                ('task_created_date', models.DateField()),
                ('task_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=20)),
                ('driver_code', models.CharField(max_length=20)),
                ('invoice_no', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
    ]
