# Generated by Django 3.1 on 2020-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_delivered_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
