# Generated by Django 3.1 on 2020-09-23 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20200923_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 23, 15, 34, 5, 489709)),
        ),
        migrations.CreateModel(
            name='Delivery_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.FileField(upload_to='delivered_doc')),
                ('id_proof', models.FileField(upload_to='delivered_doc')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.delivered')),
            ],
        ),
    ]
