# Generated by Django 3.1 on 2020-09-24 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20200923_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 24, 14, 19, 28, 571380)),
        ),
        migrations.AlterField(
            model_name='delivery_documents',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
