# Generated by Django 3.1 on 2020-09-24 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20200924_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 24, 15, 11, 7, 55119)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 24, 15, 11, 7, 60176)),
        ),
    ]
