# Generated by Django 3.1 on 2020-09-24 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20200924_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 24, 15, 19, 16, 588718)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 24, 15, 19, 16, 588718)),
        ),
    ]
