# Generated by Django 3.1 on 2020-09-25 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20200924_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_documents',
            old_name='id_proof',
            new_name='document1',
        ),
        migrations.AddField(
            model_name='delivery_documents',
            name='document2',
            field=models.FileField(null=True, upload_to='delivered_doc'),
        ),
        migrations.AddField(
            model_name='delivery_documents',
            name='document3',
            field=models.FileField(null=True, upload_to='delivered_doc'),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 25, 14, 8, 39, 961874)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 25, 14, 8, 39, 961874)),
        ),
    ]
