# Generated by Django 3.1 on 2020-09-25 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20200925_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_documents',
            name='return_item_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.returned'),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 25, 14, 48, 34, 916922)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 25, 14, 48, 34, 926005)),
        ),
    ]
