# Generated by Django 3.1 on 2020-09-28 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20200925_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 28, 15, 37, 43, 236471)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 28, 15, 37, 43, 236471)),
        ),
        migrations.CreateModel(
            name='Delivery_Docs_by_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='delivery_docs_by_admin')),
                ('task_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tasks')),
            ],
        ),
    ]
