# Generated by Django 3.1 on 2020-10-01 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_auto_20200930_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=30)),
                ('pending_tasks', models.IntegerField()),
                ('delivered_tasks', models.IntegerField()),
                ('returned_tasks', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 11, 13, 27, 100031)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 11, 13, 27, 103289)),
        ),
    ]
