# Generated by Django 3.1 on 2020-10-01 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20201001_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='status',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 11, 54, 33, 473969)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 11, 54, 33, 473969)),
        ),
    ]
