# Generated by Django 3.1 on 2020-10-01 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_auto_20201001_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='status',
        ),
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 11, 57, 43, 719278)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 11, 57, 43, 719278)),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='admin',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.admin_register'),
        ),
    ]
