# Generated by Django 3.1 on 2020-10-01 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20201001_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='delivered_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 14, 2, 33, 781444)),
        ),
        migrations.AlterField(
            model_name='returned',
            name='returned_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 14, 2, 33, 781444)),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.admin_register'),
        ),
    ]
